### ISSUE TITLE
How to cache config? 

### ISSUE THREAD

**Issue by massiws** [afiqiqmal/lara-pass-policy#2]
Running php artisan config:cache I got the error:

> Your configuration files are not serializable.

This is because in `config/lara-pass-policy.php` there is a closure:
```
    'strict' =>  \Illuminate\Validation\Rules\Password::min(8)
        ->mixedCase()
        ->numbers()
        ->symbols(),
```

How can I specify custom minimum requirements different than `Password::min(8)` , the default in `PasswordExpiredChangeController@store` ?

**Comment by masiorama** [comment]
This is indeed an issue of the package I'm dealing with too.

**Comment by massiws** [comment]
@afiqiqmal , I suggest to completely remove `strict` setting from `config/lara-pass-policy.php`, because it can't be properly cached.
A possible solution to allow users to define custom validation rules (other than `min(8)` fixed into the package controller) is to adopt the `Password::defaults` method provided by Laravel into the `PasswordExpiredChangeController` instead of the `strict` config.

What do you think about?
